"""create daily_log table

Revision ID: 3bd78e9510a4
Revises: 96bc97081601
Create Date: 2024-02-15 20:36:04.830636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bd78e9510a4'
down_revision = '96bc97081601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_log_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_log_created_at'))

    op.drop_table('daily_log')
    # ### end Alembic commands ###
